### ISSUE TITLE
Investigate memory issues with LinkForCare import job

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1623]
Steps to reproduce:
* Attempted to upload entire dataset (2400 records) - seems to have added ~300 ish record then servicenet container crashed with jvm out of memory

* Attempted to split the whole file into 200 records chunks, waiting for log 'job completed' after first chunk. Attempted to upload second chunk and also hit JVM out of memory

Not sure if this is expected (you indicated it might be) but just for completeness an error gets logged in servicenetgateway after an upload:
the only errors im seeing are in gateway service:
2021-01-15 18:35:52.287  WARN 1 --- [  XNIO-1 task-7] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
com.netflix.zuul.exception.ZuulException:
        at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.findZuulException(SendErrorFilter.java:118)
        at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:78)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
2021-01-15 18:35:52.292 DEBUG 1 --- [  XNIO-1 task-7] o.b.s.s.impl.RequestLoggerServiceImpl    : Request to save RequestLogger : RequestLoggerDTO{id=null, requestUri='/services/servicenet/api/file', remoteAddr='10.0.0.2', requestParameters='', requestBody='', responseStatus='504', requestMethod='POST', responseBody='{
  "timestamp" : "2021-01-15T18:35:52.288+0000",
  "status" : 504,
  "error" : "Gateway Timeout",
  "message" : "com.netflix.zuul.exception.ZuulException: Hystrix Readed time out"
}'}

**Comment by abaranowska1** [comment]
Looking to the Data Import Report it seems that now we are able to upload for example 2400 records.
![image](https://user-images.githubusercontent.com/61964176/105034082-4ddf4880-5a59-11eb-885f-16e09dbfd667.png)
