### ISSUE TITLE
ZonedDateTime issues during healthleads data upload job

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#818]
During HealthLeads import the metadata info seems to be causing an error relating to the processing (I believe) of last_action_date.

You can use the latest files from the example data repo. It seems to be caused by the first row - so I believe its an issue across the board not an issue with a single record.

Error output is below. Main output is 

java.time.format.DateTimeParseException: Text '2019-05-05T00:11:02.000Z' could not be parsed at index 23

The Z at the end of the string isn't present in the original data, so I'm not sure where it comes from.

```
com.google.gson.JsonParseException: Unable to parse ZonedDateTime
        at org.benetech.servicenet.util.ZonedDateTimeDeserializer.deserialize(ZonedDateTimeDeserializer.java:30)
        at org.benetech.servicenet.util.ZonedDateTimeDeserializer.deserialize(ZonedDateTimeDeserializer.java:13)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:853)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at org.benetech.servicenet.adapter.healthleads.DataResolver.getDataFromJson(DataResolver.java:27)
        at org.benetech.servicenet.adapter.healthleads.DataResolver.getDataFromJson(DataResolver.java:23)
        at org.benetech.servicenet.adapter.healthleads.HealthleadsDataAdapter.importData(HealthleadsDataAdapter.java:33)
        at org.benetech.servicenet.adapter.healthleads.HealthleadsDataAdapter.importData(HealthleadsDataAdapter.java:15)
        .
        .
        .
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.time.format.DateTimeParseException: Text '2019-05-05T00:11:02.000Z' could not be parsed at index 23
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598)
        at org.benetech.servicenet.util.ZonedDateTimeDeserializer.deserialize(ZonedDateTimeDeserializer.java:28)
        ... 161 common frames omitted
```

**Comment by kdondziak** [comment]
@johnhbenetech I think I should mention on meeting. This is caused by different format of date. In all files before it was e.g. "2019-05-05T00:11:02.000+0000" but the newest file have "2019-05-05T00:11:02.000Z". 'Z' on the end means that is time zone "UTC" -> "+0000". Can you contact to Healthleads provider and ask if they changed date format or they are using 2 formats?

**Comment by johnhbenetech** [comment]
@kdondziak Done, ill let you know when i hear back

**Comment by johnhbenetech** [comment]
@kdondziak They changed their date serializer to node. So going forward it will be the ".000Z" type format.

**Comment by bognasoldev89** [comment]
I uploaded healthleads data with new and old date format and mentioned issues don't occur anymore. I also confirmed it with @kdondziak to make sure that I don't omit anything.
