### ISSUE TITLE
Error in prod for UWBA Data Update Job

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#917]
During the most recent run of the UWBA job, it seems the data fetching portion went ok, but immediately after there were a few NPEs thrown.

It's weird because after the NPEs there are org matches run - which makes me believe the records are making it to the database, but the Job Status never updates to indicate it has completed

**Comment by johnhbenetech** [comment]
Let me know if there is something else I can tap into to be helpful. The NPEs are below:

`2020-04-08 17:41:48.309  INFO 8 --- [ryBean_Worker-1] o.b.s.adapter.icarol.RelationManager     : Saving data for ICarol: 85% completed
2020-04-08 17:41:48.313 ERROR 8 --- [ryBean_Worker-1] org.quartz.core.JobRunShell              : Job DEFAULT.UWBA Data Update Job threw an unhandled Exception:

java.lang.NullPointerException: null
        at java.base/java.util.Arrays.stream(Arrays.java:5614)
        at org.benetech.servicenet.adapter.icarol.ICarolConfidentialFieldsMapper.extractNameIfNotConfidential(ICarolConfidentialFieldsMapper.java:47)
        at org.benetech.servicenet.adapter.icarol.RelationManager.saveOrganizationsAndRelatedData(RelationManager.java:67)
        at org.benetech.servicenet.adapter.icarol.RelationManager.persist(RelationManager.java:40)
        at org.benetech.servicenet.adapter.icarol.AbstractICarolDataAdapter.importData(AbstractICarolDataAdapter.java:52)
        at org.benetech.servicenet.adapter.icarol.uwba.UWBADataAdapter.importData(UWBADataAdapter.java:20)
        at org.benetech.servicenet.adapter.icarol.uwba.UWBADataAdapter.importData(UWBADataAdapter.java:9)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.lambda$importDataIfNeeded$1(DocumentUploadServiceImpl.java:200)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.importDataIfNeeded(DocumentUploadServiceImpl.java:197)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.uploadApiData(DocumentUploadServiceImpl.java:93)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl$$FastClassBySpringCGLIB$$5b712956.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl$$EnhancerBySpringCGLIB$$eaaf12e0.uploadApiData(<generated>)
        at org.benetech.servicenet.scheduler.AbstractICarolUpdateJob.executeInternal(AbstractICarolUpdateJob.java:54)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

2020-04-08 17:41:48.317 ERROR 8 --- [ryBean_Worker-1] org.quartz.core.ErrorLogger              : Job (DEFAULT.UWBA Data Update Job threw an exception.

org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.Arrays.stream(Arrays.java:5614)
        at org.benetech.servicenet.adapter.icarol.ICarolConfidentialFieldsMapper.extractNameIfNotConfidential(ICarolConfidentialFieldsMapper.java:47)
        at org.benetech.servicenet.adapter.icarol.RelationManager.saveOrganizationsAndRelatedData(RelationManager.java:67)
        at org.benetech.servicenet.adapter.icarol.RelationManager.persist(RelationManager.java:40)
        at org.benetech.servicenet.adapter.icarol.AbstractICarolDataAdapter.importData(AbstractICarolDataAdapter.java:52)
        at org.benetech.servicenet.adapter.icarol.uwba.UWBADataAdapter.importData(UWBADataAdapter.java:20)
        at org.benetech.servicenet.adapter.icarol.uwba.UWBADataAdapter.importData(UWBADataAdapter.java:9)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.lambda$importDataIfNeeded$1(DocumentUploadServiceImpl.java:200)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.importDataIfNeeded(DocumentUploadServiceImpl.java:197)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl.uploadApiData(DocumentUploadServiceImpl.java:93)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl$$FastClassBySpringCGLIB$$5b712956.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.benetech.servicenet.service.impl.DocumentUploadServiceImpl$$EnhancerBySpringCGLIB$$eaaf12e0.uploadApiData(<generated>)
        at org.benetech.servicenet.scheduler.AbstractICarolUpdateJob.executeInternal(AbstractICarolUpdateJob.java:54)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted`

**Comment by johnhbenetech** [comment]
i *think* this is also reproducible on staging - so i wonder if it's something in a newly added record from there side that is breaking

**Comment by jkondrat** [comment]
@johnhbenetech : The error indicates that one of the agencies we got from UWBA had no names, I have added a null check in the catch block and will confirm during dry run if the error is gone. I tried running the UWBA data update job locally on an empty database, but couldn't reproduce it
